- README.md
- README_zh-CN.md
> feat: support Align-Anything-Instruction-100K dataset

- align_anything/configs/template.py
- align_anything/configs/train/text_to_audio/dpo.yaml
- align_anything/configs/train/text_to_audio/sft.yaml
- align_anything/configs/train/text_to_video/dpo.yaml
- align_anything/configs/train/text_to_video/sft.yaml
- align_anything/datasets/text_to_audio/__init__.py
- align_anything/datasets/text_to_audio/preference.py
- align_anything/datasets/text_to_audio/supervised.py
- align_anything/datasets/text_to_video/__init__.py
- align_anything/datasets/text_to_video/preference.py
- align_anything/datasets/text_to_video/supervised.py
- align_anything/models/pretrained_model.py
- align_anything/trainers/text_to_audio/__init__.py
- align_anything/trainers/text_to_audio/dpo_diffusion.py
- align_anything/trainers/text_to_audio/sft_diffusion.py
- align_anything/trainers/text_to_image/sft_diffusion.py
- align_anything/trainers/text_to_video/__init__.py
- align_anything/trainers/text_to_video/dpo_diffusion.py
- align_anything/trainers/text_to_video/sft_diffusion.py
- align_anything/utils/process_audio.py
- align_anything/utils/process_video.py
- pyproject.toml
- scripts/dpo.sh
- scripts/sft.sh
> feat: Support video/audio diffusion sft and dpo

- README.md
- README_zh-CN.md
- align_anything/models/model_registry.py
- align_anything/models/pretrained_model.py
- align_anything/trainers/base/supervised_trainer.py
- align_anything/trainers/text_to_text/kto.py
- scripts/dpo.sh
- scripts/kto.sh
- scripts/orpo.sh
- scripts/ppo.sh
- scripts/rm.sh
- scripts/sft.sh
- scripts/sft_multi_node.sh
Support SFT and DPO for the meta [chameleon model](https://huggingface.co/facebook/chameleon-7b).
Thanks to the contributions of [transformer](https://github.com/huggingface/transformers/pull/31534), we have achieved this integration with almost no effort.
If you need to use the [chameleon model](https://huggingface.co/facebook/chameleon-7b), please compile and install the latest version of transformers from the source code.
```bash
https://github.com/huggingface/transformers.git
```
For more details please refer to #18 
> feat: support chameleon

- README.md
- README_zh-CN.md
- examples/text_to_image_diffusion.md
> docs: polish README and example

- align_anything/configs/train/text_image_to_text/dpo.yaml
- align_anything/configs/train/text_image_to_text/ppo.yaml
- align_anything/configs/train/text_image_to_text/rm.yaml
- align_anything/configs/train/text_image_to_text/sft.yaml
- align_anything/configs/train/text_to_text/ppo.yaml
- align_anything/configs/train/text_to_text/rm.yaml
- align_anything/configs/train/text_to_text/sft.yaml
- align_anything/models/pretrained_model.py
- align_anything/models/pretrained_model_with_value.py
- align_anything/trainers/base/rl_trainer.py
- align_anything/trainers/base/supervised_trainer.py
- align_anything/trainers/text_image_to_text/dpo.py
- align_anything/trainers/text_image_to_text/ppo.py
- align_anything/trainers/text_image_to_text/rm.py
- align_anything/trainers/text_image_to_text/sft.py
- align_anything/trainers/text_to_text/ppo.py
> feat: add opt:freeze_language_model, rearrange yaml files

- scripts/setup.sh
There are some robustness issues with the current environment variable settings in setup.sh, which this PR will address.
> fix: fix setup.sh

- align_anything/datasets/any_to_text/__init__.py
- align_anything/datasets/text_image_to_text/__init__.py
- align_anything/datasets/text_to_audio/__init__.py
- align_anything/datasets/text_to_image/__init__.py
- align_anything/trainers/base/supervised_trainer.py
- align_anything/trainers/text_to_audio/dpo_diffusion.py
- align_anything/trainers/text_to_image/dpo_diffusion.py
- align_anything/trainers/text_to_video/dpo_diffusion.py
- align_anything/utils/tools.py
- projects/any_to_text/any_to_text.md
- Fix bugs in diffusion dpo: training model and reference model should be different models
- Add ref_diff and model_diff in wandb
> fix: diffusion dpo

- projects/lang_feedback/README.md
- projects/lang_feedback/base_gen.py
- projects/lang_feedback/critique_gen.py
- projects/lang_feedback/refine_gen.py
- projects/ti_to_ti/pre_tokenize_example.py
- projects/ti_to_ti/pre_tokenize_parallel_example.py
- projects/ti_to_ti/preference_tokenize_example.py
- projects/ti_to_ti/prompt_only_tokenize_example.py
> feat: Add language feedback for internal use

- align_anything/trainers/text_to_text/ppo.py
- align_anything/trainers/text_to_text/rm.py
> fix: fix t2t ppo

- align_anything/configs/template.py
- align_anything/configs/train/text_audio_to_text/ppo.yaml
- align_anything/configs/train/text_audio_to_text/rm.yaml
- align_anything/configs/train/text_audio_to_text/sft.yaml
- align_anything/datasets/text_audio_to_text/__init__.py
- align_anything/datasets/text_audio_to_text/preference.py
- align_anything/datasets/text_audio_to_text/prompt_only.py
- align_anything/datasets/text_audio_to_text/supervised.py
- align_anything/datasets/text_to_text/preference.py
- align_anything/models/model_registry.py
- align_anything/models/pretrained_model.py
- align_anything/models/pretrained_model_with_value.py
- align_anything/models/qwen2_audio.py
- align_anything/trainers/text_audio_to_text/__init__.py
- align_anything/trainers/text_audio_to_text/ppo.py
- align_anything/trainers/text_audio_to_text/rm.py
- align_anything/trainers/text_audio_to_text/sft.py
- align_anything/trainers/text_image_to_text/ppo.py
- align_anything/trainers/text_to_text/rm.py
- align_anything/utils/tools.py
- pyproject.toml
support qwen2-audio ppo, rm and sft
> feat: support qwen2-audio ppo, rm and sft

- README.md
> docs: polish  readme file

- README.md
- align_anything/configs/evaluation/benchmarks/air-bench.yaml
- align_anything/configs/template.py
- align_anything/evaluation/README.md
- align_anything/evaluation/__main__.py
- align_anything/evaluation/benchmarks/AIRBench/ds_evaluate.py
- align_anything/evaluation/benchmarks/AIRBench/ds_infer.py
- align_anything/evaluation/data_type.py
- docs/source/evaluation/overview.md
> feat: add new benchmark(AIRBench)

- align_anything/evaluation/benchmarks/llava-bench-coco/vllm_eval.py
- align_anything/evaluation/benchmarks/llava-bench-in-the-wild/vllm_eval.py
- align_anything/evaluation/inference/vllm_inference.py
- docs/source/conf.py
fix wrong import for llava-bench-coco
> fix: fix import for llava-bench-coco

- README.md
- align_anything/configs/format_dataset.py
- align_anything/datasets/text_audio_to_text/preference.py
- align_anything/datasets/text_audio_to_text/prompt_only.py
- align_anything/datasets/text_audio_to_text/supervised.py
- align_anything/datasets/text_image_to_text/preference.py
- align_anything/datasets/text_image_to_text/prompt_only.py
- align_anything/datasets/text_image_to_text/supervised.py
- align_anything/evaluation/benchmarks/llava-bench-coco/vllm_eval.py
- align_anything/evaluation/benchmarks/llava-bench-in-the-wild/vllm_eval.py
- align_anything/evaluation/inference/vllm_inference.py
- align_anything/models/llava_next.py
- align_anything/models/qwen2_audio.py
- align_anything/trainers/text_audio_to_text/dpo.py
- align_anything/trainers/text_audio_to_text/ppo.py
- align_anything/trainers/text_to_text/sft.py
- docs/source/conf.py
- docs/source/index.rst
- scripts/qwen2_audio_dpo.sh
- scripts/qwen2_audio_ppo.sh
- scripts/qwen2_audio_rm.sh
> refactor: clean ta2t code

- align_anything/datasets/text_audio_to_text/supervised.py
- align_anything/datasets/text_image_to_text/prompt_only.py
- align_anything/datasets/text_image_to_text/supervised.py
- align_anything/models/pretrained_model.py
> fix: fix text-to-text tokenizer

- align_anything/trainers/text_to_text/ppo.py
> fix: fix ppo infer bacth

- align_anything/configs/format_dataset.py
- align_anything/datasets/text_audio_to_text/supervised.py
- align_anything/models/minicpmo.py
- align_anything/models/model_registry.py
- align_anything/trainers/text_audio_to_text/sft.py
- scripts/minicpmo_sft_audio.sh
- scripts/minicpmo_sft_vision.sh
😊 We are very pleased to announce that align-anything now supports [openbmb/MiniCPM-o-2_6](https://huggingface.co/openbmb/MiniCPM-o-2_6) audio fine-tuning.
1. ⚙️ Install align-anything by:
```bash
pip install -e .[train]
pip install -e .[minicpmo]
```
2. 🏃 Run the training simply by:
```bash
cd scripts
bash minicpmo_sft_audio.sh
```
The training details would be:
🔍 Here is a strong demand on community: https://github.com/OpenBMB/MiniCPM-o/issues/745
> feat: support minicpm-o audio fine-tuning

- align_anything/datasets/text_audio_to_text/preference.py
- align_anything/datasets/text_image_to_text/preference.py
- align_anything/datasets/text_image_to_text/supervised.py
- align_anything/models/minicpmo.py
- align_anything/models/pretrained_model.py
- align_anything/trainers/text_audio_to_text/dpo.py
- align_anything/trainers/text_image_to_text/dpo.py
- align_anything/utils/tools.py
- scripts/minicpmo_dpo_audio.sh
- scripts/minicpmo_dpo_vision.sh
We are very pleased to announce that align-anything now supports DPO fine-tuning for minicpm-o, along with audio and image input capabilities. We have also provided two ready-to-run example scripts. Welcome to give it a try!
> feat: support minicpm-o dpo (audio & image)

- align_anything/models/minicpmo.py
This PR is a minor change to add tts chat template for audio fine-tuning.
> chore: add tts chat template

- scripts/llama_sft.sh
> fix: update train template in llama_sft.sh

- align_anything/configs/train/janus/sft.yaml
- align_anything/datasets/janus/__init__.py
- align_anything/datasets/janus/supervised.py
- align_anything/models/minicpmo.py
- align_anything/trainers/janus/__init__.py
- align_anything/trainers/janus/sft.py
- projects/README.md
- projects/janus/README.md
- projects/janus/sft_tokenize.sh
- projects/janus/supervised_t2i.py
- scripts/janus_sft.sh
😊 We are very pleased to announce that align-anything now supports [Janus](https://huggingface.co/deepseek-ai/Janus-1.3B) and [Janus Pro](https://huggingface.co/deepseek-ai/Janus-Pro-7B) fine-tuning.
⚙️ Install align-anything by:
```
pip install -e .[train]
```
🥣 Pre-tokenize the given dataset by:
```
cd align-anything/projects/janus
```
Then follow the instruction in [README.md](https://github.com/PKU-Alignment/align-anything/blob/main/projects/janus/README.md) to setup the bash script and pre-tokenize the dataset.
🏃 Run the sft training simply by:
```
cd scripts
bash janus_sft.sh
```
What types of …
> feat: support Deepseek Janus SFT

- align_anything/serve/text_modal_cli.py
- scripts/llava_next_video_rm.sh
- scripts/llava_next_video_sft.sh
> fix:fix typo in llava_next_video scripts

- align_anything/configs/train/text_to_text/grpo.yaml
- align_anything/trainers/text_to_text/grpo.py
- align_anything/trainers/text_to_text/ppo.py
- scripts/llama_grpo.sh
Support GRPO, the algorithm used to train Deepseek-math.
Close #137
> feat: support GRPO

- README.md
- scripts/setup_docker.sh
> feat: configure the environment using docker for Ascend

- README.md
- scripts/slurm_llava_dpo.sh
A new example script (scripts/slurm_llava_dpo.sh) has been added to demonstrate how to run training jobs on a Slurm-managed cluster. 
The README file has been modified to include a clear note about Slurm support. In the Training section, instructions now mention that Align-Anything fully supports migration to Slurm and direct users to the new example script for a Slurm-based training run.
close #155 
> feat: surport slurm

- README.md
- align_anything/utils/multi_process.py
- pyproject.toml
This is a minor update for ascend support.
Please test your changes by running the following command:
```bash
cd scripts
bash test/test_text_to_text.sh ./opt PATH_TO_OUTPUT_ROOT_DIR
```
Here, `./opt` is the directory containing the test scripts for the `opt` model, and `PATH_TO_OUTPUT_ROOT_DIR` is the path to the output root directory. The test scripts will save ~1GB data to the output root directory and delete it after the test. Please ensure you have enough space on your disk.
Please run the following command in the root directory to check your code style:
```bash
pip install pre-commit
pre-commit run --all-files
```
If you …
> deps: update ascend dependency

- README.md
- align_anything/models/pretrained_model.py
- cookbooks/en/text_image_to_text_sft.ipynb
- cookbooks/zh/text_image_to_text_sft.ipynb
Support `text-image-to-text` modality cookbooks. Both ZH and CN versions are available!
In these cookbooks, we show how to fine-tune llava-1.5-7b within 70 lines based on align-anything. No DeepSpeed, No Ray and No vLLM.
Please test your changes by running the following command:
```bash
cd scripts
bash test/test_text_to_text.sh ./opt PATH_TO_OUTPUT_ROOT_DIR
```
Here, `./opt` is the directory containing the test scripts for the `opt` model, and `PATH_TO_OUTPUT_ROOT_DIR` is the path to the output root directory. The test scripts will save ~1GB data to the output root directory and delete it after the test. Please ensure you have enough space on your disk.
Please run the following command in the root directory to check your code style:
```bash
pip install pre-commit
pre-commit run …
```
> fdocs: update ti2t tutorial

- align_anything/datasets/text_to_text/preference.py
- align_anything/models/model_registry.py
- align_anything/models/qwen2.py
- scripts/qwen2_5/qwen_2_5_dpo.sh
- scripts/qwen2_5/qwen_2_5_rm.sh
- scripts/qwen2_5/qwen_2_5_sft.sh
Support qwen2/qwen2.5 SFT, DPO, and RM training.
Please test your changes by running the following command:
```bash
cd scripts
bash test/test_text_to_text.sh ./opt PATH_TO_OUTPUT_ROOT_DIR
```
Here, `./opt` is the directory containing the test scripts for the `opt` model, and `PATH_TO_OUTPUT_ROOT_DIR` is the path to the output root directory. The test scripts will save ~1GB data to the output root directory and delete it after the test. Please ensure you have enough space on your disk.
Please run the following command in the root directory to check your code style:
```bash
pip install pre-commit
pre-commit run --all-files
``` …
> feat: support qwen2
